version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./front/build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SECRET=${SECRET}
      - LIFETIME=${LIFETIME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_DB_HOST=${POSTGRES_DB_HOST}

    depends_on:
      - db

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/app/build

  db:
    image: postgres:15-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_DB_PORT=5432
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  frontend_build:
