spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  minio:
    endpoint: ${MINIO_ENDPOINT}
    accessKey: ${MINIO_ACCESS_KEY}
    secretKey: ${MINIO_SECRET_KEY}
    bucket: ${MINIO_BUCKET}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    open-in-view: false

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration: ERROR

frontend:
  url: http://localhost:3000

server:
  port: 8081