spring:
  application:
    name: backend
  config:
    import: classpath:dblogin.properties

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${login}
    password: ${password}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    open-in-view: false

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration: ERROR